#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("JuzzPig.AMap.AndroidDemo.Resource", IsApplication=true)]

namespace JuzzPig.AMap.AndroidDemo
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f050000
			public const int layers_array = 2131034112;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int arrow = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int badge_sa = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int badge_wa = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int btn_default_small = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int btn_default_small_normal = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int btn_default_small_normal_disable = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int btn_default_small_pressed = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int btn_map_poi = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int btn_nav_drag_down = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int btn_nav_drag_down_normal = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int btn_nav_drag_down_pressed = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int btn_poi_search_normal = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int btn_route_next = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int btn_route_pre = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int bus = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int car = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int custom_info_bubble = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int direct_mapsearch = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int direct_mapsearch_pressed = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int divider = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int downarrow = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int end = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int groundoverlay = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int ic_launcher = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int Icon = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int icon_poisearch = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int left_back = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int location_marker = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int man = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int mode_driving = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int mode_driving_focused = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int mode_driving_off = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int mode_driving_on = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int mode_transit = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int mode_transit_focused = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int mode_transit_off = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int mode_transit_on = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int mode_walk = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int mode_walk_focused = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int mode_walk_off = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int mode_walk_on = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int next = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int next_disable = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int point = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int prev = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int prev_disable = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int rightarrow = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int search_plate_global = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int start = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int start_uri = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int text_search = 2130837554;
			
			// aapt resource value: 0x7f020033
			public const int text_search_default = 2130837555;
			
			// aapt resource value: 0x7f020034
			public const int text_search_pressed = 2130837556;
			
			// aapt resource value: 0x7f020035
			public const int text_search_selected = 2130837557;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f06002c
			public const int ListView_nav_search_list_poi = 2131099692;
			
			// aapt resource value: 0x7f06000b
			public const int Lujiazui = 2131099659;
			
			// aapt resource value: 0x7f060036
			public const int RelativeLayout_roadsearch_top = 2131099702;
			
			// aapt resource value: 0x7f06000c
			public const int Zhongguancun = 2131099660;
			
			// aapt resource value: 0x7f060014
			public const int alphaSeekBar = 2131099668;
			
			// aapt resource value: 0x7f06000a
			public const int animate = 2131099658;
			
			// aapt resource value: 0x7f06003a
			public const int autotextview_roadsearch_goals = 2131099706;
			
			// aapt resource value: 0x7f060039
			public const int autotextview_roadsearch_start = 2131099705;
			
			// aapt resource value: 0x7f060016
			public const int badge = 2131099670;
			
			// aapt resource value: 0x7f06004f
			public const int bottom_center = 2131099727;
			
			// aapt resource value: 0x7f06004e
			public const int bottom_left = 2131099726;
			
			// aapt resource value: 0x7f060050
			public const int bottom_right = 2131099728;
			
			// aapt resource value: 0x7f06003b
			public const int btn_layout = 2131099707;
			
			// aapt resource value: 0x7f060001
			public const int busName = 2131099649;
			
			// aapt resource value: 0x7f060008
			public const int busid = 2131099656;
			
			// aapt resource value: 0x7f060007
			public const int busname = 2131099655;
			
			// aapt resource value: 0x7f060046
			public const int buttonScale = 2131099718;
			
			// aapt resource value: 0x7f06001b
			public const int camera_text = 2131099675;
			
			// aapt resource value: 0x7f060034
			public const int city = 2131099700;
			
			// aapt resource value: 0x7f060002
			public const int cityName = 2131099650;
			
			// aapt resource value: 0x7f060026
			public const int clearMap = 2131099686;
			
			// aapt resource value: 0x7f060049
			public const int compass_toggle = 2131099721;
			
			// aapt resource value: 0x7f06002a
			public const int custom_info_contents = 2131099690;
			
			// aapt resource value: 0x7f06002b
			public const int custom_info_window = 2131099691;
			
			// aapt resource value: 0x7f060028
			public const int custom_info_window_options = 2131099688;
			
			// aapt resource value: 0x7f060029
			public const int default_info_window = 2131099689;
			
			// aapt resource value: 0x7f06001c
			public const int description = 2131099676;
			
			// aapt resource value: 0x7f060041
			public const int firstfloor = 2131099713;
			
			// aapt resource value: 0x7f06001e
			public const int geoButton = 2131099678;
			
			// aapt resource value: 0x7f060013
			public const int hueSeekBar = 2131099667;
			
			// aapt resource value: 0x7f060038
			public const int imagebtn_roadsearch_endoption = 2131099704;
			
			// aapt resource value: 0x7f06003f
			public const int imagebtn_roadsearch_search = 2131099711;
			
			// aapt resource value: 0x7f060037
			public const int imagebtn_roadsearch_startoption = 2131099703;
			
			// aapt resource value: 0x7f06003d
			public const int imagebtn_roadsearch_tab_driving = 2131099709;
			
			// aapt resource value: 0x7f06003c
			public const int imagebtn_roadsearch_tab_transit = 2131099708;
			
			// aapt resource value: 0x7f06003e
			public const int imagebtn_roadsearch_tab_walk = 2131099710;
			
			// aapt resource value: 0x7f060033
			public const int keyWord = 2131099699;
			
			// aapt resource value: 0x7f060020
			public const int layers_spinner = 2131099680;
			
			// aapt resource value: 0x7f060006
			public const int listview = 2131099654;
			
			// aapt resource value: 0x7f060031
			public const int locationButton = 2131099697;
			
			// aapt resource value: 0x7f06004d
			public const int logo_position = 2131099725;
			
			// aapt resource value: 0x7f060000
			public const int map = 2131099648;
			
			// aapt resource value: 0x7f060045
			public const int map_container = 2131099717;
			
			// aapt resource value: 0x7f060040
			public const int map_screenshot = 2131099712;
			
			// aapt resource value: 0x7f060025
			public const int mark_listenter_text = 2131099685;
			
			// aapt resource value: 0x7f060024
			public const int marker_text = 2131099684;
			
			// aapt resource value: 0x7f060023
			public const int marker_title = 2131099683;
			
			// aapt resource value: 0x7f060022
			public const int myLocation = 2131099682;
			
			// aapt resource value: 0x7f06004a
			public const int mylocation_toggle = 2131099722;
			
			// aapt resource value: 0x7f060005
			public const int nextButton = 2131099653;
			
			// aapt resource value: 0x7f06001f
			public const int online_user_list_item_textview = 2131099679;
			
			// aapt resource value: 0x7f060044
			public const int opentile = 2131099716;
			
			// aapt resource value: 0x7f06002e
			public const int poiAddress = 2131099694;
			
			// aapt resource value: 0x7f06002d
			public const int poiName = 2131099693;
			
			// aapt resource value: 0x7f060004
			public const int preButton = 2131099652;
			
			// aapt resource value: 0x7f06001d
			public const int regeoButton = 2131099677;
			
			// aapt resource value: 0x7f060027
			public const int resetMap = 2131099687;
			
			// aapt resource value: 0x7f060019
			public const int root = 2131099673;
			
			// aapt resource value: 0x7f060047
			public const int scale_toggle = 2131099719;
			
			// aapt resource value: 0x7f06000f
			public const int scroll_down = 2131099663;
			
			// aapt resource value: 0x7f06000d
			public const int scroll_left = 2131099661;
			
			// aapt resource value: 0x7f060010
			public const int scroll_right = 2131099664;
			
			// aapt resource value: 0x7f06004b
			public const int scroll_toggle = 2131099723;
			
			// aapt resource value: 0x7f06000e
			public const int scroll_up = 2131099662;
			
			// aapt resource value: 0x7f060032
			public const int searchButton = 2131099698;
			
			// aapt resource value: 0x7f060030
			public const int searchType = 2131099696;
			
			// aapt resource value: 0x7f060003
			public const int searchbyname = 2131099651;
			
			// aapt resource value: 0x7f060042
			public const int secondfloor = 2131099714;
			
			// aapt resource value: 0x7f060018
			public const int snippet = 2131099672;
			
			// aapt resource value: 0x7f06002f
			public const int spinnerdeep = 2131099695;
			
			// aapt resource value: 0x7f060035
			public const int start_amap_app = 2131099701;
			
			// aapt resource value: 0x7f060009
			public const int stop_animation = 2131099657;
			
			// aapt resource value: 0x7f06001a
			public const int tap_text = 2131099674;
			
			// aapt resource value: 0x7f060043
			public const int thridfloor = 2131099715;
			
			// aapt resource value: 0x7f060017
			public const int title = 2131099671;
			
			// aapt resource value: 0x7f060021
			public const int traffic = 2131099681;
			
			// aapt resource value: 0x7f060015
			public const int widthSeekBar = 2131099669;
			
			// aapt resource value: 0x7f06004c
			public const int zoom_gestures_toggle = 2131099724;
			
			// aapt resource value: 0x7f060011
			public const int zoom_in = 2131099665;
			
			// aapt resource value: 0x7f060012
			public const int zoom_out = 2131099666;
			
			// aapt resource value: 0x7f060048
			public const int zoom_toggle = 2131099720;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int basicmap_activity = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int busline_activity = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int busline_dialog = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int busline_item = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int camera_activity = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int circle_activity = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int custom_info_contents = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int custom_info_window = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int empty = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int events_activity = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int expandablelistviewselector = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int feature = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int geocoder_activity = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int groundoverlay_activity = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int item = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int layers_activity = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int location = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int locationnetwork_activity = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int locationsource_activity = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int main_activity = 2130903059;
			
			// aapt resource value: 0x7f030014
			public const int marker = 2130903060;
			
			// aapt resource value: 0x7f030015
			public const int marker_activity = 2130903061;
			
			// aapt resource value: 0x7f030016
			public const int navsearch_list_poi = 2130903062;
			
			// aapt resource value: 0x7f030017
			public const int poi_result_list = 2130903063;
			
			// aapt resource value: 0x7f030018
			public const int poiaroundsearch_activity = 2130903064;
			
			// aapt resource value: 0x7f030019
			public const int poikeywordsearch_activity = 2130903065;
			
			// aapt resource value: 0x7f03001a
			public const int poikeywordsearch_uri = 2130903066;
			
			// aapt resource value: 0x7f03001b
			public const int polygon_activity = 2130903067;
			
			// aapt resource value: 0x7f03001c
			public const int polyline_activity = 2130903068;
			
			// aapt resource value: 0x7f03001d
			public const int route_activity = 2130903069;
			
			// aapt resource value: 0x7f03001e
			public const int route_inputs = 2130903070;
			
			// aapt resource value: 0x7f03001f
			public const int routesearch_list_poi = 2130903071;
			
			// aapt resource value: 0x7f030020
			public const int screenshot_activity = 2130903072;
			
			// aapt resource value: 0x7f030021
			public const int tileoverlay_activity = 2130903073;
			
			// aapt resource value: 0x7f030022
			public const int ui_settings_activity = 2130903074;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040000
			public const int animate = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int basic_description = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int basic_map = 2130968577;
			
			// aapt resource value: 0x7f04005c
			public const int bottom_center = 2130968668;
			
			// aapt resource value: 0x7f04005b
			public const int bottom_left = 2130968667;
			
			// aapt resource value: 0x7f04005d
			public const int bottom_right = 2130968669;
			
			// aapt resource value: 0x7f040037
			public const int busline_demo = 2130968631;
			
			// aapt resource value: 0x7f040038
			public const int busline_description = 2130968632;
			
			// aapt resource value: 0x7f040059
			public const int buttonScale = 2130968665;
			
			// aapt resource value: 0x7f040003
			public const int camera_demo = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int camera_description = 2130968580;
			
			// aapt resource value: 0x7f040030
			public const int circle_demo = 2130968624;
			
			// aapt resource value: 0x7f040031
			public const int circle_description = 2130968625;
			
			// aapt resource value: 0x7f040005
			public const int clear_map = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int compass = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int custom_info_contents = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int custom_info_window = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int default_info_window = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int demo_title = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public const int down_arrow = 2130968587;
			
			// aapt resource value: 0x7f04000c
			public const int drag_melbourne = 2130968588;
			
			// aapt resource value: 0x7f040060
			public const int error_key = 2130968672;
			
			// aapt resource value: 0x7f04005f
			public const int error_network = 2130968671;
			
			// aapt resource value: 0x7f040061
			public const int error_other = 2130968673;
			
			// aapt resource value: 0x7f04000d
			public const int events_demo = 2130968589;
			
			// aapt resource value: 0x7f04000e
			public const int events_description = 2130968590;
			
			// aapt resource value: 0x7f040010
			public const int fill_color = 2130968592;
			
			// aapt resource value: 0x7f04000f
			public const int fill_stroke = 2130968591;
			
			// aapt resource value: 0x7f040049
			public const int geocoder_demo = 2130968649;
			
			// aapt resource value: 0x7f04004a
			public const int geocoder_description = 2130968650;
			
			// aapt resource value: 0x7f040012
			public const int go_to_lujiazui = 2130968594;
			
			// aapt resource value: 0x7f040011
			public const int go_to_zhongguancun = 2130968593;
			
			// aapt resource value: 0x7f04002c
			public const int groundoverlay_demo = 2130968620;
			
			// aapt resource value: 0x7f04002d
			public const int groundoverlay_description = 2130968621;
			
			// aapt resource value: 0x7f040013
			public const int hybrid = 2130968595;
			
			// aapt resource value: 0x7f040015
			public const int layers_demo = 2130968597;
			
			// aapt resource value: 0x7f040016
			public const int layers_description = 2130968598;
			
			// aapt resource value: 0x7f040017
			public const int left_arrow = 2130968599;
			
			// aapt resource value: 0x7f040014
			public const int location = 2130968596;
			
			// aapt resource value: 0x7f04001a
			public const int locationGPS_demo = 2130968602;
			
			// aapt resource value: 0x7f04001b
			public const int locationGPS_description = 2130968603;
			
			// aapt resource value: 0x7f04001d
			public const int locationNetwork_demo = 2130968605;
			
			// aapt resource value: 0x7f04001c
			public const int locationNetwork_description = 2130968604;
			
			// aapt resource value: 0x7f040018
			public const int locationsource_demo = 2130968600;
			
			// aapt resource value: 0x7f040019
			public const int locationsource_description = 2130968601;
			
			// aapt resource value: 0x7f04005a
			public const int logo_position = 2130968666;
			
			// aapt resource value: 0x7f040020
			public const int mapOption_demo = 2130968608;
			
			// aapt resource value: 0x7f040021
			public const int mapOption_description = 2130968609;
			
			// aapt resource value: 0x7f040022
			public const int map_not_ready = 2130968610;
			
			// aapt resource value: 0x7f04005e
			public const int map_screenshot = 2130968670;
			
			// aapt resource value: 0x7f04001e
			public const int marker_demo = 2130968606;
			
			// aapt resource value: 0x7f04001f
			public const int marker_description = 2130968607;
			
			// aapt resource value: 0x7f040023
			public const int move_the_camera = 2130968611;
			
			// aapt resource value: 0x7f040024
			public const int my_location = 2130968612;
			
			// aapt resource value: 0x7f040025
			public const int mylocation_layer = 2130968613;
			
			// aapt resource value: 0x7f040026
			public const int no_demos = 2130968614;
			
			// aapt resource value: 0x7f040062
			public const int no_result = 2130968674;
			
			// aapt resource value: 0x7f040027
			public const int normal = 2130968615;
			
			// aapt resource value: 0x7f04004f
			public const int offlinemap_demo = 2130968655;
			
			// aapt resource value: 0x7f040050
			public const int offlinemap_description = 2130968656;
			
			// aapt resource value: 0x7f04004d
			public const int poiaroundsearch_demo = 2130968653;
			
			// aapt resource value: 0x7f04004e
			public const int poiaroundsearch_description = 2130968654;
			
			// aapt resource value: 0x7f04004b
			public const int poikeywordsearch_demo = 2130968651;
			
			// aapt resource value: 0x7f04004c
			public const int poikeywordsearch_description = 2130968652;
			
			// aapt resource value: 0x7f040028
			public const int polygon_demo = 2130968616;
			
			// aapt resource value: 0x7f040029
			public const int polygon_description = 2130968617;
			
			// aapt resource value: 0x7f04002a
			public const int polyline_demo = 2130968618;
			
			// aapt resource value: 0x7f04002b
			public const int polyline_description = 2130968619;
			
			// aapt resource value: 0x7f040036
			public const int properties_circle = 2130968630;
			
			// aapt resource value: 0x7f040035
			public const int properties_polygon = 2130968629;
			
			// aapt resource value: 0x7f040034
			public const int properties_polyline = 2130968628;
			
			// aapt resource value: 0x7f04003c
			public const int reset_map = 2130968636;
			
			// aapt resource value: 0x7f04003d
			public const int right_arrow = 2130968637;
			
			// aapt resource value: 0x7f04003b
			public const int rotate = 2130968635;
			
			// aapt resource value: 0x7f040039
			public const int route_demo = 2130968633;
			
			// aapt resource value: 0x7f04003a
			public const int route_description = 2130968634;
			
			// aapt resource value: 0x7f04003e
			public const int satellite = 2130968638;
			
			// aapt resource value: 0x7f040058
			public const int scale = 2130968664;
			
			// aapt resource value: 0x7f040032
			public const int screenshot_demo = 2130968626;
			
			// aapt resource value: 0x7f040033
			public const int screenshot_description = 2130968627;
			
			// aapt resource value: 0x7f04003f
			public const int scroll = 2130968639;
			
			// aapt resource value: 0x7f040051
			public const int search_title = 2130968657;
			
			// aapt resource value: 0x7f040040
			public const int stop_animation = 2130968640;
			
			// aapt resource value: 0x7f040041
			public const int stroke_width = 2130968641;
			
			// aapt resource value: 0x7f040042
			public const int tap_instructions = 2130968642;
			
			// aapt resource value: 0x7f040043
			public const int terrain = 2130968643;
			
			// aapt resource value: 0x7f04002e
			public const int tileoverlay_demo = 2130968622;
			
			// aapt resource value: 0x7f04002f
			public const int tileoverlay_description = 2130968623;
			
			// aapt resource value: 0x7f040044
			public const int tilt = 2130968644;
			
			// aapt resource value: 0x7f040045
			public const int traffic = 2130968645;
			
			// aapt resource value: 0x7f040046
			public const int transparency = 2130968646;
			
			// aapt resource value: 0x7f040047
			public const int uisettings_demo = 2130968647;
			
			// aapt resource value: 0x7f040048
			public const int uisettings_description = 2130968648;
			
			// aapt resource value: 0x7f040052
			public const int up_arrow = 2130968658;
			
			// aapt resource value: 0x7f040053
			public const int width = 2130968659;
			
			// aapt resource value: 0x7f040054
			public const int zoom_buttons = 2130968660;
			
			// aapt resource value: 0x7f040055
			public const int zoom_gestures = 2130968661;
			
			// aapt resource value: 0x7f040056
			public const int zoom_in = 2130968662;
			
			// aapt resource value: 0x7f040057
			public const int zoom_out = 2130968663;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
